### PR TITLE
Add XFCE Xfwm4 windows manager theme

### PR DESCRIPTION
**Pull request by lvancrayelynghe**

### CODE REVIEW

**Comment by Benoth** [comment]
You can see the result here http://imgur.com/a/7dOFD

**Comment by vooze** [comment]
Looks really good. Will take a look at it tomorrow. It's late in Denmark :-)

**Comment by lvancrayelynghe** [comment]
You can see the result here sorry, had to fix the screenshoot http://imgur.com/a/7dOFD (it's late in France too ... ahem ;))

**Comment by lvancrayelynghe** [comment]
Fixed the non OSX version and added screenshoot on Imgur

**Comment by vooze** [comment]
Looks good! That being said, thunar looks a bit weird with the blue (leftover from orignal arc) in the "url" bar.. But if you use Nemo like you, it should be fine. Might look into that later.

**Comment by lvancrayelynghe** [comment]
I think it's the "active button" state from gtk2. I'll give it a try !

image

**Pull request merged**
