### PR TITLE
Bring back Gtk3 assets rendering, using the new assets

### PR DESCRIPTION
**Pull request by lvancrayelynghe**
Since you were targeting mostly Unity, I'm not sure you'll be interested by this PR ? Tell me what you think, if you agree with that, I'll make a huge cleanup (half of the assets are unused^^).

Hope I did not broke anything between the two versions ? The difference is not yet clear for me !

### CODE REVIEW

**Comment by lvancrayelynghe** [comment]
Gtk3 apps screenshoots (under XFCE again) : http://imgur.com/a/acYMY !

**Comment by lvancrayelynghe** [comment]
Fixed the non OSX version and added screenshoot on Imgur

**Comment by vooze** [comment]
Looks good, I even see you found some mistakes with gtk3 assets :) Do you need to do some cleaning before I pull? Thank you!

**Comment by lvancrayelynghe** [comment]
You can merge, I'll create another PR. I need time to clean everything (cleanup the svg file and remove unused png files). But it works as is ;)

**Comment by vooze** [comment]
Perfect, I'll do that :) I'm just now installing xubuntu to check the other pull request, and then I'll merge that.

**Pull request merged**
